[phases.setup]
nixPkgs = ["php", "redis"]

[variables]
NIXPACKS_PHP_VERSION = "8.5"

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link || true && php artisan serve --host=0.0.0.0 --port=$PORT"